# Generated by Django 5.0.7 on 2024-08-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurses', '0001_initial'),
        ('patients', '0002_patient_delete_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='current_patients',
            field=models.ManyToManyField(related_name='nurses', to='patients.patient'),
        ),
    ]
