# Generated by Django 5.0.7 on 2024-08-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='current_patients',
        ),
    ]
