# Generated by Django 5.0.7 on 2024-08-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_medicalrecord_user_medicalrecord_patient_and_more'),
        ('pharmacists', '0002_drug_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prescriptions',
            field=models.ManyToManyField(blank=True, related_name='patients', to='pharmacists.prescription'),
        ),
    ]
