# Generated by Django 5.0.7 on 2024-08-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacists", "0003_prescription_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="date_filled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
