# Generated by Django 5.0.7 on 2024-08-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacists", "0004_prescription_date_filled"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="filled",
            field=models.BooleanField(default=False),
        ),
    ]
