# Generated by Django 5.0.7 on 2024-08-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacists", "0005_prescription_filled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescription",
            old_name="date_filled",
            new_name="last_filled",
        ),
    ]
