# Generated by Django 5.0.7 on 2024-08-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_nurse',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_patient',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_pharmacist',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
